### ISSUE TITLE
[FRONTEND] LOG ENTRY PAGE (CREATE / UPDATE / DELETE / READ(print) VIEW )

### ISSUE THREAD

**Issue by AroraShreshth** [EngineerLogbook/logbook#14]
Personal LOG Create Update Delete View

**Comment by growupboron** [comment]
@akshit-mee Please collaborate with @taz2419.

**Comment by growupboron** [comment]
@taz2419 @MagnumDingusEdu safe to close this issue?

**Comment by AroraShreshth** [comment]
The CRUD parts are somethings that need to be developed in specific different html files indepently with there own attached views this Issue is going to remain open for long
